### PR TITLE
Create config.yaml

### PR DESCRIPTION
**Pull request by omeryounus**

### CODE REVIEW

**Comment by ovitrif** [comment]
Hi @omeryounus , thanks for your pull request!

**Comment by ovitrif** [comment]
Out of curiosity, may I know what this config file is useful for?
Thanks in advance!

**Comment by omeryounus** [comment]
H iOvi Trif, This is for Circle CI config file. So if you push any changes it will take to Circle CI and build and test cases.

**Comment by ovitrif** [comment]
Awesome, thanks again!
I'm merging it :)

**Pull request merged**
